# app/schemas/answer.py
# Day 5: Request/Response schemas for answer generation

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from app.schemas.query import RetrievedChunk  # Reuse from Day 4


class AnswerRequest(BaseModel):
    """Request for answer generation (full RAG)."""
    
    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="The question to answer"
    )
    
    document_ids: Optional[List[int]] = Field(
        None,
        description="Filter to specific documents (optional)"
    )
    
    top_k: Optional[int] = Field(
        5,
        ge=1,
        le=20,
        description="Number of chunks for context"
    )
    
    stream: Optional[bool] = Field(
        False,
        description="Stream answer tokens as they arrive"
    )


class SourceReference(BaseModel):
    """A document source that contributed to the answer."""
    
    document_id: int = Field(description="Document ID")
    filename: str = Field(description="Document filename")
    page_number: Optional[int] = Field(None, description="Page number if applicable")
    relevance: float = Field(description="Similarity score (0-1)")


class AnswerResponse(BaseModel):
    """Response with LLM-generated answer."""
    
    question: str = Field(description="The question that was asked")
    
    answer: str = Field(
        description="Natural language answer generated by LLM"
    )
    # Example: "Based on the contract, it expires on December 31st, 2025."
    
    retrieved_chunks: List[RetrievedChunk] = Field(
        description="Chunks used to generate answer"
    )
    
    sources: List[SourceReference] = Field(
        description="Unique documents referenced in answer"
    )
    
    chunk_count: int = Field(
        description="Number of chunks used"
    )
    
    response_time_ms: float = Field(
        description="Total time to generate answer (ms)"
    )


class StreamingAnswerChunk(BaseModel):
    """Chunk in streaming answer response."""
    
    type: str = Field(
        description="'chunks', 'token', 'error', or 'complete'"
    )
    
    token: Optional[str] = Field(
        None,
        description="Single token (if type='token')"
    )
    
    retrieved_chunks: Optional[List[RetrievedChunk]] = Field(
        None,
        description="Chunks (if type='chunks')"
    )
    
    error: Optional[str] = Field(
        None,
        description="Error message (if type='error')"
    )
