# app/core/agent/graph.py
#
# Builds the LangGraph ReAct agent.
#
# WHY `create_react_agent` (not a manual StateGraph):
# - Day 6's goal is to GET AN AGENT WORKING, not reimplement ReAct from scratch.
# - LangGraph ships a prebuilt that handles the Thought → Action → Observation loop.
# - In Day 7+ when we add streaming, or Day 8 when we add clause comparison,
#   we'll either (a) keep using this prebuilt with extra tools, or
#   (b) graduate to a custom StateGraph when we need custom routing logic.
#
# WHAT THIS RETURNS:
# - A compiled `StateGraph` you call `.ainvoke({"messages": [HumanMessage(q)]})` on.
# - Returns a dict with the full message history including all tool calls/results.
# - The `messages` list is what `AgentService` walks to build the response.

from typing import Optional
from sqlalchemy.orm import Session

from langgraph.prebuilt import create_react_agent

from app.core.agent.llm import build_chat_model
from app.core.agent.tools import build_tools


def build_agent(
    db: Session,
    user_id: int,
    document_ids: Optional[list[int]] = None,
    top_k: int = 5,
):
    """
    Build a compiled LangGraph ReAct agent.

    Args:
        db: SQLAlchemy session (request-scoped, per-user)
        user_id: owner of the documents
        document_ids: optional filter to specific documents
        top_k: chunks to retrieve per search

    Returns:
        CompiledStateGraph: call `.ainvoke({"messages": [HumanMessage(q)]})`.

    Example:
        agent = build_agent(db, user_id=1)
        result = await agent.ainvoke({
            "messages": [HumanMessage(content="When does the contract expire?")]
        })
        # result["messages"] is the full conversation
    """
    llm = build_chat_model()
    tools = build_tools(db, user_id, document_ids, top_k)

    # `create_react_agent` returns a compiled graph with the ReAct loop baked in.
    # The system prompt is auto-generated by LangGraph from tool descriptions,
    # so our careful docstrings in tools.py matter a lot.
    agent = create_react_agent(
        model=llm,
        tools=tools,
    )

    return agent